import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from '@/components/Navbar'
import SideBar from '@/components/SideBar'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function layout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <div style={{
          width: "100%",
          zIndex: "10",
          overflow: "hidden"
        }}>
          <Navbar />
        </div>
        <div style={{
          display: "flex",
          // flexWrap: "wrap",
        }}>
          <div>
            <SideBar />
          </div>
          <div style={{
            flex: 1,
            backgroundColor: "#F2F2F2",
            maxWidth: "100%",
            height: "100%",
            padding: "40px",
          }}>
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
